### ISSUE TITLE
grpc demo problem

### ISSUE THREAD

**Issue by dingrui37** [p4lang/PI#147]
I want to run the grpc demo(PI/protp/demo_grpc), but I can find the file pi_grpc_server and controller as the
guide descriped.
```
    sudo python 1sw_demo.py --json simple_router.json --cpu-port veth250
    sudo ./pi_grpc_server
    sudo ./controller -c simple_router.json

```

**Comment by antoninbas** [comment]
You need to follow the README instructions and build all the code: https://github.com/p4lang/PI/tree/master/proto/demo_grpc. Make sure you install all the dependencies, otherwise it may silently skip building the demo code.
Assuming you have all the dependencies, you need to run at the top-level:
- `./configure --with-proto --with-bmv2`
- `make`
