### ISSUE TITLE
Question: What does write INSERT operation do for Meter and Counter externs?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/PI#177]
Reference to the code: https://github.com/p4lang/PI/blob/master/proto/p4/p4runtime.proto#L221-L233

Copied here for easy reading:
```
//------------------------------------------------------------------------------
// For WriteRequest, Update.Type has following semantics:
//  - INSERT: Insert the cell in the meter array (with given configuration)
//  - MODIFY: Modify the meter cell configuration
//  - DELETE: Delete the meter cell (i.e. reset the meter configuration)
// For ReadRequest, the scope is defined as follows:
// - All meter cells for all meters if meter_id = 0 (default).
// - All meter cells for given meter_id if index = 0 (default).
message MeterEntry {
  uint32 meter_id = 1;
  int64 index = 2;
  MeterConfig config = 3;
}
```
The comments say that a WriteRequest INSERT operation inserts a cell in the meter array.

My understand of a P4_14 meter (one that is not direct) is that the P4_14 program must define the number of meters in the array, and this is typically (or always?) a compile time constant.  If true, there is no way that control plane code could create a new one at run time.  Perhaps this could be made to happen by forcing the P4_14 program to be recompiled with a larger number of meters in the array, but is that the intent of this WriteRequest INSERT operation?  If not, I would recommend that a WriteRequest INSERT operation on a meter should be a no-op, perhaps returning an error status.

For a direct meter, they are associated 1-to-1 with entries in a table.  Thus adding an entry to the corresponding table automatically creates the corresponding meter state, and deleting an entry from a table automatically deletes the corresponding meter state.  If so, I would recommend that a WriteRequest INSERT operation on a direct meter should be a no-op, perhaps returning an error status.

The same questions/comments apply for WriteRequest INSERT operations on counters and direct counters.

For a WriteRequest DELETE operation on a meter, it isn't clear to me what "reset the meter configuration" means?

**Comment by antoninbas** [comment]
This is a very good observation and an issue that I brought up before. I think the idea was to have some symmetry for all write operations. Notice how we have managed to simplify the API to have a single Write RPC and a single Read RPC. This makes it very convenient to send a batch of operations.
No matter how much I think about it, I can't find a scenario in which having an INSERT operation would make sense for direct resources... For indirect counters and meters, I would be a little bit more nuanced. If you see the indirect counter array as a pool from which you can request counter cells, then the INSERT operation could correspond to requesting a cell from the pool. However, because we use the notion of "index" to access counter cells (rather than arbitrary ids like for action profiles), it still doesn't make more sense. BTW, according to the comments in the protobuf, an "index" of 0 is not a valid value, which may be an issue.
I think this warrants some additional discussion / clarification so I'll be sure to bring this up. BTW in my current implementation, I treat INSERT and MODIFY in exactly the same way...

One thing that is missing IMO is the ability to push an initial configuration for direct resources (e.g. meter rates) when adding a table entry. That's something we should consider adding.

**Comment by jafingerhut** [comment]
The ability for the control plane to specify, for a direct meter, what the default initial configuration of meter rates, sounds like a useful addition.

For indirect counters and meters, I am pretty sure that most/all P4 implementations effectively have all counters/meters in the array available for updating as soon as the P4 program is loaded onto the device, regardless of whether the control plane performs any operations on them.  At least, I'd appreciate it if anyone corrected me if I have a misconception there.

**Comment by antoninbas** [comment]
Hopefully this is clear in the current version of the spec, so I'm closing this
