### ISSUE TITLE
Question:  What are the meaning of some proto message's fields?

### ISSUE THREAD

**Issue by dingrui37** [p4lang/PI#183]
I am a bit confused about some fields. I really want to know the exact meaning of them. Every question start with 'Q' character. Sorry for my poor English. 

```
message StreamMessageRequest {
  oneof update {
    MasterArbitrationUpdate arbitration = 1;  //Q1: why we need this field?  when and where
                                              //need to set this field?
    PacketOut packet = 2;
  }
}

// Packet sent from the controller to the switch.
message PacketOut {
  bytes payload = 1;
  oneof pipeline {                 //Q2: what's the difference between setting and 
                                   //not setting the pipeline field?
    uint32 egress_physical_port = 2; 
//Q3:If I set the egress_physical_port field, why the packet still pass to the pipeline 
//(parser->ingress->egress)? I think if this filed is set, the packet shouldn't pass 
//to the pipeline, it will be transport out of the egress_physical_port directly. 

    IngressPipelineSpec ingress_pipeline_spec = 3;
//Q4:Does this field(ingress_pipeline_spec) means we can choose a specific pipeline for 
//the packet?
  }
}

message IngressPipelineSpec {
  // Ingress port to associate with the packet.
  uint32 ingress_port = 1;
}

message StreamMessageResponse {
  oneof update {
    MasterArbitrationUpdate arbitration = 1;
    PacketIn packet = 2;
  }
}

// Packet sent from the switch to the controller.
message PacketIn {
  bytes payload = 1;
  uint32 ingress_physical_port = 2;
  uint32 ingress_logical_port = 3; 
 //Q5: Are the ingress_logical_port and ingress_logical_port  fields not support now?  
 //Because they are all zero when received, and I want to know who will set these fields? 
}

message MasterArbitrationUpdate {
  uint64 device_id = 1;
  // The stream RPC with the highest election_id is the master. The 'master'
  // controller instance populates this with its latest election_id. Switch
  // populates with the highest election ID it has received from all connected
  // controllers.
  Uint128 election_id = 2;
  // Switch populates this with OK for the client that is the master, and with
  // an error status for all other connected clients (at every mastership
  // change). The controller does not populate this field.
  .google.rpc.Status status = 3;
}
```

**Comment by antoninbas** [comment]
The `arbitration` field is used to enable to controller-replication. In a nutshell, and if I oversimplify, each controller is assigned an arbitration id; the controller with the highest id is the master and can issue `Write` requests to the switch, all the other controllers are slaves.
There is a similar concept in OpenFlow, so you can look there if you want to get a better idea for what it is and why we need it.
We will be documenting this feature before the end of the year when we release a specification document for P4Runtime. Note that for now, this feature is not even implemented.

All the other fields you are asking about do not exist any more (update your p4runtime.proto copy).

**Comment by dingrui37** [comment]
@antoninbas Thanks.  Is there an example of how to use Packet-on and Packet-out based on the latest version. After updating, I am even more confused.

**Comment by antoninbas** [comment]
If I were you I would ignore the `repeated PacketMetadata` field in the `PacketIn` and `PacketOut` messages for now, and simply use the `payload` field. Then I hope it becomes straightforward to use based on this example: https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch_grpc/tests/test_packet_io.cpp

The `PacketMetadata` feature is not available for P4_14 programs. If you are using P4_16 with the new p4c compiler, you can use it but it may not provide a lot of value. The way packet IO works in P4 is you usually define a CPU header which is used to encapsulate packets exchanged between the switch and the controller. Because of the P4 protocol-independence, this header is usually not treated any differently than other headers and would simply be transmitted in binary format at the head of the `payload` field in `PacketIn` / `PacketOut`.
If for some reason, you want to give a special status to this CPU header and you do not want to transmit it as binary data in `P4Runtime`, then you can use the `PacketMetadata` feature. Here is a detailed example taken from an email I wrote some time back:

The packet-in and packet-out headers can be defined like this in P4_16:
```
@controller_header("packet_in")
header packet_in_header_t {
    bit<9> ingress_port;
    bit<32> other1;
}

@controller_header("packet_out")
header packet_out_header_t {
    bit<9> egress_port;
    bit<32> other2;
}
```

These definitions then show up in the p4info produced by the compiler:
```
controller_packet_metadata {
  preamble {
    id: 2868941301
    name: "packet_in"
    annotations: "@controller_header(\"packet_in\")"
  }
  metadata {
    id: 1
    name: "ingress_port"
    bitwidth: 9
  }
  metadata {
    id: 2
    name: "other1"
    bitwidth: 32
  }
}
controller_packet_metadata {
  preamble {
    id: 2868916615
    name: "packet_out"
    annotations: "@controller_header(\"packet_out\")"
  }
  metadata {
    id: 1
    name: "egress_port"
    bitwidth: 9
  }
  metadata {
    id: 2
    name: "other2"
    bitwidth: 32
  }
}
```
Notice how the order of the fields in the p4info is guaranteed to be the same as in the P4 program.

Now if we look at the PacketOut message in p4runtime.proto:
```
// Packet sent from the controller to the switch.
message PacketOut {
  bytes payload = 1;
  // This will be based on P4 header annotated as
  // @controller_header("packet_out").
  // At most one P4 header can have this annotation.
  repeated PacketMetadata metadata = 2;
}
```

The repeated metadata fields correspond to the ones in p4info. Because the `PacketMetadata` message includes the id, each field can be mapped to its p4info "definition" and for each field we can obtain 1) its bitwidth 2) its offset in the header. In the switch implementation, we use this information to generate a binary header which is prepended to the binary `payload`. The resulting packet is injected in the P4 dataplane.

**Comment by dingrui37** [comment]
I'm sorry, I didn't respond in time. Last week I went to Beijing to join a SDNFV confrence.  ChangHoon Kim made a speech about P4 tech in the confrence, but he was so busy, I had no opportunity to ask him questions.  I will go on my work this week.
