### ISSUE TITLE
Communication between P4 program and PI program

### ISSUE THREAD

**Issue by Yukinarii** [p4lang/PI#221]
Hello, I'm new to P4, and just start for PI/PD. I have read something examples about PI library,and know how to insert/delete an entry from tables, but doesn't find anything about how P4 program and PI program communicates,so I want to ask about how P4 program informs the PI program to start to insert/delete an entry?

**Comment by antoninbas** [comment]
I'm confused about your question. "P4 program and PI program" don't communicate. The P4 program is used to define the forwarding dataplane. The control-plane software can then manage the forwarding elements of this dataplane, which include match-action tables, by using the P4 Runtime (aka PI) API. In particular, this API lets the control-pane insert & delete entries from match-action tables. The decision to insert & delete entries is taken by the control-plane, and is independent of the P4 program.
However, the format of table entries is indeed dictated by the P4 program. Which is why as part of the P4 Runtime project, we have created P4Info (https://github.com/p4lang/PI/blob/master/proto/p4/config/p4info.proto). P4Info is a message that contains information relevant to the control-plane, extracted from the P4 program. P4Info is generated from the p4 program by the compiler (https://github.com/p4lang/p4c/). For example, it tells the control-plane which tables were defined in the P4 program, what is the format of the match key for each table, what is the list of possible actions for each tables, etc...
Make sure you read this blog post for an introduction to P4 Runtime: https://p4.org/api/announcing-p4runtime-a-contribution-by-the-p4-api-working-group/

**Comment by Yukinarii** [comment]
Thanks for response. I think I understand it better now,and get some idea to solve the problems in my project.

**Comment by antoninbas** [comment]
@Yukinarii what this re-opened for a reason?

**Comment by Yukinarii** [comment]
Sorry, just a wrong click.
