### ISSUE TITLE
Multi-controller support in P4 Runtime

### ISSUE THREAD

**Issue by antoninbas** [p4lang/PI#233]
There are several use cases for which one may want to have multiple controllers talking to the same P4 Runtime switch (we use the term "controller" loosely to designate a remote SDN controller or some local control-plane agent):
- partitioning of P4 objects (e.g. one controller for L2/L3, one controller for ACL, etc.)
- in the case of a SDN controller, some functionality may be offloaded to the local switch software (e.g. LACP agent)
- multiple controllers may be interested in packet-in messages

If we want to support these use cases, we will need to redefine the notion of master-slave arbitration (https://github.com/p4lang/PI/blob/master/proto/docs/arbitration.md). The current p4runtime.proto supports a single master which can perform `Write` operations on all P4 tables, receives `PacketIn` messages and sends `PacketOut` messages.

We need to come up with a proposal on how to support the above use cases in P4 Runtime.

**Comment by jafingerhut** [comment]
Another use case for motivating multiple controllers that would be useful to document.  I think it is covered in one or more of the categories you mention above, but wanted to call it out explicitly, since it caused significant discussion in the PSA working group:

+ a local controller with low round trip time in the control path to a PSA device, that can update one or more action selectors for fast-reroute on link failures.  Something similar to the watch port functionality of OpenFlow, and fast reroute capabilities as implemented in multiple commercial non-programmable switch ASICs.

This seems like it ought to fall under the category of partitioning the P4 objects between controllers.

**Comment by HvR-Netronome** [comment]
Another user case is for P4 develop environment:

To have a debugger "connected" via the PI as controller to gather data to display to the developer while having the normal controller use as per normal for typical test cases.

**Comment by wmohsin** [comment]
Proposal (to be discussed in API-WG on Nov 29):
https://docs.google.com/a/google.com/document/d/1eIsBsPFn219TCgKgVndiCOok02-FyyMlL4tXuEl1aLI/edit?usp=sharing

**Comment by antoninbas** [comment]
See #286

**Comment by antoninbas** [comment]
#286 has been merged
