### ISSUE TITLE
"all-or-nothing" and "stop-on-error" mode for Write batches

### ISSUE THREAD

**Issue by antoninbas** [p4lang/PI#290]
Right now we only support "continue-on-error" (https://github.com/p4lang/PI/blob/master/proto/docs/p4runtime.md#error-reporting)

Should we add an enum to the `WriteRequest` message to support other modes ("all-or-nothing" and "stop-on-error")?

This could wait until after v1.0.

**Comment by jafingerhut** [comment]
"all-or-nothing" can be challenging to implement if the intent is that the data plane should not be touched at all if "all" would fail.  Not impossible, but with things like hash tables to implement several common table types, it effectively means an agent has to maintain a shadow copy of all table state as it would be, in memory, without touching the data plane, for all operations in the batch.  At the end of that, if no operations fail "in memory", then go through and actually write them to the data plane.  If not, then revert the agent's state to the data plane's state (either because you kept a snapshot of it before starting the validation of the batch, or you undo the in-memory effects of the portion of the batch you've validated so far).

Or does "all-or-nothing" mean it is OK to start doing data plane updates one at a time, and if any fails, then undo data plane updates (perhaps in reverse order they were done, in case the order matters?).

"stop-on-error" is pretty easy to implement, by comparison.

**Comment by antoninbas** [comment]
Decision at the 02/21/2018 WG meeting was to add an enum to choose between "continue-on-error" and "all-or-none" modes. p4runtime.proto and spec need to be updated.

**Comment by antoninbas** [comment]
See WG decision here: https://docs.google.com/document/d/16gvs3Y196ptz38ujEc9tCGMSm_Elv2I5WdrtEUU3jd0
Closing this issue in favor of #324
