### ISSUE TITLE
Question: Using dp-grpc-addr/packet_in/packet_out

### ISSUE THREAD

**Issue by FollowingGhosts** [p4lang/PI#311]
Hi all,

I'm trying to make sense of the P4Runtime gRPC and am falling down on a point that doesn't seem particularly clear.

When running the simple_switch_grpc example with --dp-grpc-serv-addr, packets seem to get caught in a black hole, and are not parsed when sent in on interfaces specified with the `-i` flag. I had assumed the cpu port was acting as the proxy for this and would serve as the source/destination for packets sent here.

Do they need to instead be sent to the switch over gRPC or is this a known bug?

Secondly, I am unsure on how to work with the `packet_in` and `packet_out` messages defined in the p4 proto. How can I cause them to be generated? is it as simple as adding the annotation `controller_header("packet_out")` to my p4 programs or am I missing a step/steps?

Thanks in advance for help with what are probably fairly straightforward questions. I'd been fighting the dp-grpc-serv-addr dropping packets for far too long.

**Comment by antoninbas** [comment]
The whole point of `--dp-grpc-serv-addr` is that it lets you send & receive dataplane packets through gRPC and not through libpcap. So `--dp-grpc-serv-addr` is _not meant to be used along with the `-i` flag_. It is a different way of sending and receiving traffic, which may be more appropriate for unit testing and large scale emulation. Note that unlike P4Runtime, this gRPC service is specific to bmv2.

`--dp-grpc-serv-addr` is completely independent of CPU / controller packets. Controller packets are meant to be sent (packet-out) and received (packet-in) through the P4Runtime interface directly. Adding the annotation is nice because it enables automatic serialization / deserialization of the controller header by the P4Runtime server, but it is not a must-have. In P4, controller packets are processed like any other packet. A packet sent to the CPU port will trigger a P4Runtime packet-in message to the P4Runtime client. If the P4Runtime client send a packet-out message, the packet will show up in the P4 datapath on the CPU port. When using bmv2 simple_switch_grpc, you can chose the CPU port value you want to use with `--cpu-port`. More details on controller packets here: https://github.com/p4lang/PI/issues/183#issuecomment-319161250
