### ISSUE TITLE
Should proto messages include string names in addition to ids?

### ISSUE THREAD

**Issue by antoninbas** [p4lang/PI#33]
for debugging purposes mostly

**Comment by HvR-Netronome** [comment]
We are definitely in support for having string names for all entities.

Makes debugging a lot easier and the "unified ID" system can be quite confusing and I can imagine hard for possible future third party controller developers to use.

Another issue this will solve if we can have string name for rules, as it stand (AFAIK) rules are only identified by their match fields, sort of like a TCAM model. This makes the editing of match fields impossible and what can be a simple edit operation now turns into a rule remove and rule add operations.

Third problem is making bmv2-p4 compatible implementations, since bmv2 makes use of a segregated entity system is make it really hard to be both bmv2 and p4 compatible without implemting dual ID system.

**Comment by antoninbas** [comment]
Hi @HvR-Netronome 

This was discussed at the P4 API WG meeting yesterday (please refer to minutes).
The original rationale for using IDs instead of names was to ensure smaller messages, as P4_16 fully-qualified names can be quite long (even though one could make the argument that smaller unique suffixes could be used). Another reason is P4 dataplane update: members of the WG have expressed interest in being able to have stable IDs when changes are made to the program (this can include changes to the fully-qualified name).

The original issue was about adding an _optional_ name field in the messages for debugging purposes; this is still on the table, even though there was concern at the WG meeting that some overhead would be incurred even when the field is not set. In any case, it seems that everyone present at the meeting yesterday agreed that we should not _require_ this field to be present; and target implementations should not rely on the name being present in the message.

Note that the fully-qualified name can be retrieved easily thanks to the P4Info message, which is available to the target implementation.

Identifying match-table rules by their match-key was a design choice I believe. In any case, this is a different issue from the one discussed here IMO.

Finally, I don't believe the bmv2 design choices should have an impact on P4 Runtime design. I don't recall running into too many issues when implementing P4 Runtime on bmv2.

**Comment by HvR-Netronome** [comment]
Thank you for the feedback Antonin. 

Will be glad if the optional names get included as we can then ensure it use at least with out tools

**Comment by antoninbas** [comment]
Very little interest in this from people participating in P4 API WG activities. I am removing this from the P4Runtime v1.0 release milestone; the issue can be revisited after the release.

**Comment by antoninbas** [comment]
Closing this since no more activity on this thread. Feel free to re-open this issue in the P4Runtime repo (https://github.com/p4lang/p4runtime) if this is still a desired feature for you.
