### ISSUE TITLE
Support for multiple controllers

### ISSUE THREAD

**Issue by sajishv** [p4lang/PI#338]
Hi, 

We have a situation where we need two controllers (remote and local control plane) to connect to simple_switch_grpc at the same time and perform write operations on the same set of tables.

I came across the recent change https://github.com/p4lang/PI/pull/286 which happens to solve our issue with 'role_id' however I did not notice the corresponding changes in pi_server implementation. 

Could you please let me know if the support for role-id in pi_server is in progress.

Thanks,
Sajish.

**Comment by antoninbas** [comment]
We definitely plan on having a reference implementation for this. However I am not sure about the timeline. One tricky part is that we haven't looked at how to define role configurations (or scopes) yet. We agreed that it would be out-of-scope for P4Runtime v1.0 (scheduled for release at the end of May), and we use an "Any" protobuf message for the role configuration (https://github.com/p4lang/PI/blob/master/proto/p4/p4runtime.proto#L470) so that we can support arbitrary schemes.

It is likely that we will publish a companion document to P4Runtime v1.0 spec later in the year describing one (or more) possible ways of describing controller roles - and it will eventually be implemented in pi_server and / or Stratum (https://stratumproject.org/).

In the mean time, if you want to use multiple controllers with pi_server, you can always skip master-arbitration altogether. pi_sever always accepts `Write` RPCs when no master has been set and the `role_id` and `election_id` fields are not set (i.e. default to 0) in the `WriteRequest` message.

**Comment by sajishv** [comment]
Thanks for the clarification. 
I was able to fix my issue with your suggested approach.

**Comment by coolvikas** [comment]
Hi @antoninbas, Is the refernce implementaion completed as of now with the release of new specification ( https://s3-us-west-2.amazonaws.com/p4runtime/docs/master/P4Runtime-Spec.html) for connecting two controllers at same time with simple_switch_grpc?

**Comment by antoninbas** [comment]
No, there cannot really be support for this in the reference implementation until the P4 API WG defines some standard way of defining roles / partitioning the P4 objects.
Note that P4Runtime v1.0 spec states that role definition schemes are out-of-scope of the document.

**Comment by jafingerhut** [comment]
Does the current reference server implementation allow simultaneous client connections according to this note in one of your earlier comments?

"In the mean time, if you want to use multiple controllers with pi_server, you can always skip master-arbitration altogether. pi_sever always accepts Write RPCs when no master has been set and the role_id and election_id fields are not set (i.e. default to 0) in the WriteRequest message."

**Comment by antoninbas** [comment]
This workaround should still work for Write RPCs as long as the clients don't go through master arbitration. However if they don't go through master arbitration they cannot receive PacketIn messages.
