### ISSUE TITLE
MAC_LEARN SAVING ADDRESSES IN THE SWITCH INSTEAD OF RECEIVER

### ISSUE THREAD

**Issue by Chriss4P** [p4lang/PI#365]
Hi everyone,
I have an issue to code a mac_learn action in the P4 switch saving new source addresses IN the switch (so, without using the generate_digest action because it saves in the receiver).
Where can I save the addresses? With which action or function? Can I use a C code in .p4 file?
please, can your help me?
Greetings,

Chriss

**Comment by hesingh** [comment]
You cannot use C code in a .p4 file.   Any reason why you didn't think of using a P4 table to save your data?

Also, see this text in the P4-16 specification 

[For example, the following program fragment uses a list expression to pass several header fields simultaneously to a learning provider:

extern LearningProvider {
    void learn<T>(in T data);
}
LearningProvider() lp;

lp.learn( { hdr.ethernet.srcAddr, hdr.ipv4.src } );
]

**Comment by antoninbas** [comment]
This question is unrelated to this repository which is dedicated to P4 runtime APIs.

You are asking about hardware learning which is not supported by P4_14 and not supported by either of the P4_16 standard architectures (v1model and PSA). A easy way to hack up some hardware learning support would be to modify the implementation of the learning engine in bmv2: https://github.com/p4lang/behavioral-model/blob/master/src/bm_sim/learning.cpp#L615. Instead of adding the learnt sample to a buffer (which is then send to the receiver), you can use the sample to insert a new entry in the table (if you can find a way to get a reference to the appropriate bmv2 table instance).

The more correct way to do it is to define your own P4_16 architecture that support hardware learning through a new extern (it can be identical to v1model in every other way), then implement support for your new extern in bmv2-simple_switch. That's probably some more work.

I'm closing this issue since it is independent of this repo (actually if you do hardware learning there is little need for runtime APIs...). Once you do some more investigation, feel free to open an issue in the appropriate repository (bmv2, p4c) or on to ask your questions on the p4-dev mailing list.

**Comment by ranouch** [comment]
hi hesingh ,
you can explain me a little bit more because I have the same problem.

**Comment by hesingh** [comment]
@ranouch Since this issue is closed, could you please join the p4-dev mailer if you haven't already.  

http://lists.p4.org/mailman/listinfo/p4-dev_lists.p4.org

As Antonin has also said, please send any questions to the p4-dev mailer.
