### ISSUE TITLE
target independent CLI 

### ISSUE THREAD

**Issue by snifbh** [p4lang/PI#411]
Would it be possible to detach the CLI from target implementation?
I think that the CLI should get a P4RT info file (instead of a bmv2 json file),

CLI is not updated to grpc.
for example when compiling --with-proto
then the CLI will simply use grpc to send the command to a server that the target should create.
This way the PI will really be Platform Independent...

**Comment by antoninbas** [comment]
Hi Omer. Most of the CLI code is target independent, although some minor changes are required to CLI/main.c to accept a p4info & binary file instead of the bmv2 JSON. You are right that ideally the CLI should be using P4Runtime as a backend and not some custom RPC mechanism (as is the case now). PI & the CLI actually predates P4Runtime which is why things are as they are. Unfortunately I haven't had time to work on updating the CLI to use P4Runtime. Such a project would belong in a different repository (either p4lang/p4runtime, or if we want to keep code separate from interface definition, a new p4lang/p4runtime-cli repo).
Maybe eventually I'll get to this but if someone from the community wants to get started, they should feel free to reach out to me.

**Comment by jafingerhut** [comment]
I would suggest that if someone wanted to create a CLI, consider relying on a `python` interactive session, giving you not only the power of CLI commands via Python functions for operations like adding/removing table entries/etc., but also the full power of a programming language to do looping, data structures, etc.  You can avoid doing the programming language stuff if you don't need it, but it is there if you do.

**Comment by antoninbas** [comment]
Project started here: https://github.com/p4lang/p4runtime-shell
Everyone is welcome to provide feedback / contribute

**Comment by antoninbas** [comment]
Closing this.
Feel free to open issue on https://github.com/p4lang/p4runtime-shell for feature requests.
If there is a need for a different kind of P4Runtime CLI, this should be discussed in a https://github.com/p4lang/p4runtime issue.
