### ISSUE TITLE
why some target apis without device_id param ?

### ISSUE THREAD

**Issue by lxlmummy** [p4lang/PI#506]
Hi, when I read the target API(include/PI/target/*.h) , I find  some target apis without device_id param. api like， __pi_session_init，_pi_session_cleanup，_pi_batch_begin，_pi_batch_end.
as for  __pi_session_init API，
why design as
pi_session_init(pi_session_handle_t *session_handle)
why not design as
pi_session_init(pi_dev_id_t dev_id, pi_session_handle_t *session_handle)

In my mind, a DeviceMgr instantiate is for per device. If pi_session_init（）has no device_id param，how can the multi-line-cards(multi device) to distinction which device will deal with this rpc(pi_session_init) ？ for example, there are two line cards, they may both receive the rpc(pi_session_init) , In realy there should be only one card to deal this rpc, if not with deivce_id，Both two line cards will recevice this rpc.

If I understand something wrong about p4runtime spect？or this is a bug?

**Comment by antoninbas** [comment]
First, PI is just an implementation of P4Runtime - or more precisely a convenience library to help map P4Runtime messages to lower-level vendor-specific SDK calls - , so understanding how PI works is not required to understand P4Runtime. Understanding PI is only required if you need to support P4Runtime on a new target and you wish to leverage PI for the implementation.

Second, the PI internal RPC support (https://github.com/p4lang/PI/tree/master/targets/rpc) is considered deprecated. We believe it is no longer required since P4Runtime itself can be used for RPC.

Third, a quick not on the PI functions:
 * no leading underscore indicates that it is a public function; these functions are called by the P4Runtime server code
 * one leading underscore indicates that it is a function whose implementation needs to be provided by the target (the prototypes for these functions are under (include/PI/target/). For example bmv2 implements these functions in this folder: https://github.com/p4lang/behavioral-model/tree/master/PI/src
 * two leading underscores indicate that this function was used for the internal PI RPC implementation; as indicated above, this is now deprecated

Now to answer your question directly, these functions (`pi_session_init`, `pi_batch_begin`, etc.) don't take the device as parameter by design: a PI session or a PI batch can span multiple devices (unlike in P4Runtime). For example, using a single batch, I can perform table updates across multiple devices. PI doesn't exactly define what a "session" is (and bmv2 always ignores the session parameter), but it may be useful for some targets.

**Comment by lxlmummy** [comment]
@antoninbas I will need to support P4Runtime on my own target device，If there is a problem, I will consult you again. Thank you for your patience and careful explanation.
