### ISSUE TITLE
Missing pi_table_entry_t initialization

### ISSUE THREAD

**Issue by bocon13** [p4lang/PI#507]
`pi_table_entry_t` is not initialized to zero.

https://github.com/p4lang/PI/blob/3b5737656411bbac146102ca16302c1b274b0ec9/proto/frontend/src/device_mgr.cpp#L1125

cc: @craigsdell

**Comment by antoninbas** [comment]
Hi Brian. How does the issue manifest itself? Some initialization can be done in `pi_table_default_action_get`, but ultimately the target-specific implementation (_pi_table_default_action_get) is in charge of populating all `pi_table_entry_t` fields correctly. Which PI implementation is creating issues?

**Comment by craigsdell** [comment]
The entry->direct_res_config pointer is referenced in the parse_direct_resources function and if it is not null it is assumed to be a valid structure, which will mostly like cause a crash if it is indeed just random data.  

While this could be fixed by setting this field in all the _pi_table_default_action_get implementations it doesn't appear to be set by say the BMV2 implementation when the action type is DATA and I wasn't setting it in my new NP4 Intel (FPGA) implementation.  I'd say it's probably safe to init all the fields at run time using pi_table_entry_t entry{} or pi_table_entry_t entry{PI_ACTION_ENTRY_TYPE_NONE, nullptr}.

This was initially working in my older stratum build environment based on the old private repo of Stratum but when we switched to the current public fork of stratum I found this problem (BTW only happens after writing a bunch of tables and then doing a read, assume it requires a certain amount of recycling of memory on the stack).  Quite possible that there is either a compiler or compiler flag change in the environment that has caused these stack-based structs not to be initialised now.

**Comment by antoninbas** [comment]
Thanks for the details Craig. I pushed a patch for this. BTW, it seems that the PI implementation used by bmv2 simple_switch_grpc and Stratum sets this field correctly: https://github.com/p4lang/behavioral-model/blob/master/PI/src/pi_tables_imp.cpp#L364. However, the legacy implementation which is no longer really used but is still part of the PI repository wasn't doing it: https://github.com/p4lang/PI/blob/master/targets/bmv2/pi_tables_imp.cpp

**Comment by craigsdell** [comment]
Great thanks Antonin
