### ISSUE TITLE
ControllerPacketMetaData object in P4Info not being parsed 

### ISSUE THREAD

**Issue by prakashbadri** [p4lang/PI#548]
We are using the  P4Runtime server PI reference library  (https://github.com/p4lang/PI) in Arista EOS for our P4Runtime server implementation.

One thing I see is that the ControllerPacketMetaData object is never parsed into the p4info object. In pi::p4info::p4info_proto_reader(), the following objects are parsed. (tables, actions, action profiles, counters, meters,digests )
"""  
    read_actions(p4info_proto, *p4info);
    read_tables(p4info_proto, *p4info);
    read_act_profs(p4info_proto, *p4info);
    read_counters(p4info_proto, *p4info);
    read_meters(p4info_proto, *p4info);
    read_digests(p4info_proto, *p4info);
"""

But I don't see the reading of the ControllerPacketMetaData information. I am making the changes to include that as well. But I wanted to raise the issue and make sure that I was not missing something obvious.

**Comment by antoninbas** [comment]
Hi @prakashbadri - this information is not included in the p4info struct because the assumption is that the P4Runtime server will serialize metadata fields and prepend them to the packet data before invoking PI: https://github.com/p4lang/PI/blob/main/proto/frontend/src/packet_io_mgr.cpp. The rationale is that the controller header (which defines these metadata fields) is no different from any other packet header in the P4 program, and needs to be parsed by the device in the same way.

If you only need to include this information to the p4info struct, with no change to the PI API, then it is a pretty straightforward and non-controversial change. But if you want to change the PI API so that it accepts metadata field values as a separate parameter (and not serialized at the front of the packet, then it is a more disruptive change: https://github.com/p4lang/PI/blob/b2760a818e0b8ade5864604d29b3008a684c6d5f/include/PI/pi.h#L118

One solution for the latter would be to introduce an alternative function to the API, e.g. `pi_packetout_send_with_metadata`. We can also expose a different method to query the target API preference. This is something we already do for action profile programming: https://github.com/p4lang/PI/blob/4961fb9fb7a03b8fe7f1511f05fc7a0238b1d88c/include/PI/pi_act_prof.h#L145. The target can then indicate to the server code which of the 2 functions to use and we can update the reference server code in this repo to support both options.

**Comment by prakashbadri** [comment]
Hi Antonin,
Sorry for the delayed response.  I am fixing it by adding the packetIn/packetOut metadata info to the p4Info struct rather than changing or creating a PI API.

**Comment by prakashbadri** [comment]
Thanks for quick response by the way. I was out for a couple of weeks due to some personal emergency. So could not respond right away

**Comment by antoninbas** [comment]
Did you mean to close this issue? Don't you want to submit a PR to add that support (adding the packetIn/packetOut metadata info to the p4Info struct)?
